plugins {
    id 'java-library'
    id 'maven-publish'
}

archivesBaseName = 'gchart'
version = '2.7-tt'

repositories {
    mavenCentral()
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

java {
    withJavadocJar()
    withSourcesJar()
}

dependencies {
    // GWT client only
    compileOnly "com.google.gwt:gwt-user:2.8.1"
}

tasks.register('customJar', Jar) {
    from sourceSets.main.java.srcDirs
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = 'sk.turn'
            artifactId = 'clientsidegchart'
            version = '2.7-tt'
            artifact customJar
        }
    }
}
